Writer: add marker support
OpenTimelineIO/otio-aaf-adapter pull request #47
Opened 2024-05-24 22:02 UTC by timlehr

I added marker support, including all supported colors in the Avid MC.

**Known issues**

When a marker is on the first frame of a track it will break the transcription and I'm not sure why. The markers will simply not show up in the Avid.

2024-05-24 22:12 UTC, timlehr commented
@markreidvfx maybe you can help me out on this one. I can't figure out why a marker on 0 would break things.

2025-03-13 17:15 UTC, jminor commented
Notes from meeting:
- Mark suggests checking to see how transitions influence the position of markers. There's some subtlety to how those interact.
- For the 0-frame issue, it would be helpful to compare to an AAF written out from Media Composer.
- Maybe a sample AAF showing the problem could be useful.

2026-02-02 13:03 UTC, lbarral requested changes
We suggest some more care is taken in preserving the multi-slot nature of Marker storage in the AAF, which can't be achieved in the current implementation as it hard-codes most of it.

2026-02-02 13:03 UTC, lbarral commented on src/otio_aaf_adapter/adapters/aaf_adapter/aaf_writer.py
> +    def transcribe_aaf_descriptive_markers(self):
This method is not being called from anywhere - is that intentional?

2026-02-02 13:03 UTC, lbarral commented on src/otio_aaf_adapter/adapters/aaf_adapter/aaf_writer.py
> +        marker['DescribedSlots'].value = {1, 2, 3, 4, 10, 11}
We see the list of described slots hard-coded here.
Ideally, it would be relevant to preserve the described slot in the OTIO metadata, so it can be properly re-created back.
note: Avid's MediaComposer will not look past the first entry in this list and will, by default, create markers in the first picture track.
In case we cannot preserved the slot ID being referred to by this event slot, we would recomment to use the First Picture slot ID being generated. With it being hard-coded as is, it will always default to the Timecode track in the translation from OTIO

2026-02-02 13:03 UTC, lbarral commented on src/otio_aaf_adapter/adapters/aaf_adapter/aaf_writer.py
> +        event_mob_slot['SlotID'].value = 1000
We shouldn't have an hard-code slot ID value here. It is also possible that there are more than one Event Mob Slots.
Media Composer will create one Event  Mob Slot for each Essence track/slot to which markers were added.

2026-06-26 19:50 UTC, timlehr commented on src/otio_aaf_adapter/adapters/aaf_adapter/aaf_writer.py
> +    def transcribe_aaf_descriptive_markers(self):
Good catch, I think that was a cherry-pick merge issue from our internal branch!

2026-06-26 19:53 UTC, timlehr commented
@lbarral Hey Luis, thank you for the extensive feedback. I found some time to finally get back on this and did an extensive rewrite of the code, after analyzing more samples exported from MC and taking your comments into account. Please have another look if you find some time.

2026-09-11 23:45 UTC, stefanschulze approved these changes
looks great! I did test this in my local sandbox, everything worked fine, code look good!

2026-09-12 00:10 UTC, merged