Time warp fixes: Trim-to-fill
OpenTimelineIO/otio-aaf-adapter pull request #54
Opened 2024-12-12 08:31 UTC by jminor

Fixes https://github.com/jminor/otio-time-warp-test-suite/issues/2

This PR attempts to fix the AAF->OTIO conversion of trim-to-fill time warp effects. Previously, they were translated as generic TimeEffects without any information (just a dump of AAF metadata). Now they are detected as LinearTimeWarp effects and a time_scalar is computed from keyframes and/or SpeedRatio.

Note, this PR is a draft. Further unit tests need to be added to verify correct behavior.

Also note that I did this work on top of @markreidvfx 's #44 but I believe this PR could be separated from that one, since the change is unrelated.

2024-12-18 08:07 UTC, jminor commented
I have rebased this onto the main branch instead of Mark's PR so we have the option of landing this before or after that.

I have added a unit test which checks the time warp effect type and linear `time_scale` value. Currently several of the time scale values are incorrect & need to be investigated in more detail.

2025-03-08 02:37 UTC, jminor commented
This PR now includes work from @kathryn184 which fixes reverse time warps also :)

2025-03-10 05:26 UTC, timlehr requested changes
Thanks @jminor! This looks good to me. Just the note about the changes from #56 being reversed.

2025-03-10 05:26 UTC, timlehr commented on src/otio_aaf_adapter/adapters/advanced_authoring_format.py
> +def write_to_file(input_otio, filepath, **kwargs):
This undoes the work recently merged in #56.

2025-03-10 05:26 UTC, timlehr commented on src/otio_aaf_adapter/adapters/advanced_authoring_format.py
> +        otio2aaf = aaf_writer.AAFFileTranscriber(timeline, f, **kwargs)
Same: This undoes the work recently merged in #56.

2025-03-11 04:18 UTC, jminor commented on src/otio_aaf_adapter/adapters/advanced_authoring_format.py
> +def write_to_file(input_otio, filepath, **kwargs):
Oops. Fixed.

2025-03-11 04:18 UTC, jminor commented on src/otio_aaf_adapter/adapters/advanced_authoring_format.py
> +        otio2aaf = aaf_writer.AAFFileTranscriber(timeline, f, **kwargs)
Oops. Fixed.

2025-03-13 02:18 UTC, timlehr approved these changes

2025-03-13 19:32 UTC, merged